DROP TABLE "REPORT";
DROP TABLE "QNA";
DROP TABLE "LIKE";
DROP TABLE "PST_CATEGORY";
DROP TABLE "MEMBER_GRADE";
DROP TABLE "REPLY_REPORT";
DROP TABLE "REPLY_LIKE";
DROP TABLE "POST_LIKE";
DROP TABLE "MEMBER_REPORT";
DROP TABLE "STORE";            -- 왜안들감?
DROP TABLE "NOTICEBOARD_POST"; --길어서 안들어감
DROP TABLE "FILE";
DROP TABLE "MEMBER";
DROP TABLE "MENU";
DROP TABLE "REPLY";
DROP TABLE "BRAND";
DROP TABLE "REPORT";
DROP TABLE "QNA";
DROP TABLE "LIKE";
DROP TABLE "PST_CATEGORY";
DROP TABLE "MEMBER_GRADE";
DROP TABLE "REPLY_REPORT";
DROP TABLE "REPLY_LIKE";
DROP TABLE "POST_LIKE";
DROP TABLE "MEMBER_REPORT";
DROP TABLE "STORE";            -- 왜안들감?
DROP TABLE "NOTICEBOARD_POST"; --길어서 안들어감
DROP TABLE "FILE";
DROP TABLE "MEMBER";
DROP TABLE "MENU";
DROP TABLE "REPLY";
DROP TABLE "BRAND";
DROP TABLE "REPORT";
DROP TABLE "QNA";
DROP TABLE "LIKE";
DROP TABLE "PST_CATEGORY";
DROP TABLE "MEMBER_GRADE";
DROP TABLE "REPLY_REPORT";
DROP TABLE "REPLY_LIKE";
DROP TABLE "POST_LIKE";
DROP TABLE "MEMBER_REPORT";
DROP TABLE "STORE";            -- 왜안들감?
DROP TABLE "NOTICEBOARD_POST"; --길어서 안들어감
DROP TABLE "FILE";
DROP TABLE "MEMBER";
DROP TABLE "MENU";
DROP TABLE "REPLY";
DROP TABLE "BRAND";

----------------------------
----- 회원번호 시퀀스 드랍 -----
----------------------------
DROP SEQUENCE SEQ_MNO;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MEMBER';

------------------------------
-- 회원 번호(MEMBER_NO) 시퀀스 --
------------------------------
CREATE SEQUENCE SEQ_MNO
NOCACHE;

-----------------------------
------- 회원 정보 테이블 -------
-----------------------------
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(12) NOT NULL UNIQUE,
    MEMBER_PWD VARCHAR2(15) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE NUMBER NOT NULL,
    BIRTH DATE,
    GENDER CHAR(3) CHECK(GENDER IN ('남', '여')),
    ADDRESS VARCHAR2(150),
    BLACKLIST CHAR(1) DEFAULT 'N',
    MEMBER_POINT NUMBER DEFAULT 0,
    STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '회원닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.BLACKLIST IS '블랙리스트여부';
COMMENT ON COLUMN MEMBER.MEMBER_POINT IS '회원포인트';
COMMENT ON COLUMN MEMBER.STATUS IS '탈퇴여부';

-- 더미데이터
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'admin', 'admin', '관리자', '관리자', 'daknawa@gmail.com', '01012345678', NULL, NULL, NULL, DEFAULT, 100, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user01', 'pass01', '치킨좀먹어본놈', '홍길동', 'honggd@gmail.com', '01011112222', NULL, '남', '서울시 영등포구', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user02', 'pass02', '치킨쿤', '차보해', 'chickenkun@gmail.com', '01077779999', '1998-04-08', '남', '강원도 원주시', DEFAULT, DEFAULT, DEFAULT);
----------------------------------------

CREATE TABLE "MENU" (
	"MENU_ID"	NUMBER		NOT NULL,
	"MENU_NAME"	VARCHAR2(90)		NOT NULL,
	"MENU_PRICE"	NUMBER		NOT NULL,
	"MENU_CATEGORY"	VARCHAR2(90)		NOT NULL,
	"STORE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "STORE" (
	"STORE_ID"	NUMBER		NOT NULL,
	"STORE_NAME"	VARCHAR2(90)		NOT NULL,
	"STORE_ADDSS"	VARCHAR2(300)		NOT NULL,
	"STORE_PHONE"	CHAR(11)		NULL,
	"STORE_TIME"	VARCHAR2(1000)		NULL,
	"MAP_LAT"	VARCHAR2(10)		NULL,
	"MAP_LNG"	VARCHAR2(10)		NULL,
	"BRAND_ID"	VARCHAR(15)		NOT NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_CATEGORY"	VARCHAR(15)		NULL,
	"REPORT_HISTORY"	VARCHAR2(1000)		NULL,
	"REPORT_TYPE"	NUMBER		NULL,
	"REPORT_ANSWER"	VARCHAR2(1000)		NULL,
	"PST_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "NOTICEBOARD_POST" (
	"PST_ID"	NUMBER		NOT NULL,
	"PST_TITLE"	VARCHAR2(150)		NULL,
	"POST_IN"	VARCHAR2(1500)		NULL,
	"PST_VIEW"	NUMBER		NULL,
	"PST_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"PST_DEL"	CHAR(1)	DEFAULT 'Y'	NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"POSTLIST"	NUMBER		NOT NULL
);

CREATE TABLE "QNA" (
	"ASK_NO"	NUMBER		NOT NULL,
	"ASK_TYPE"	NUMBER	DEFAULT 1	NULL,
	"ASK_TITLE"	VARCHAR(15)		NULL,
	"ASK_CONTENT"	VARCHAR2(300)		NULL,
	"ASK_DATE"	VARCHAR2(100)		NULL,
	"ANSWER_CONTENT"	VARCHAR2(300)		NULL,
	"ANSWER_DATE"	VARCHAR2(100)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "BRAND" (
	"BRAND_ID"	VARCHAR2(15)		NOT NULL,
	"BRAND_NAME"	VARCHAR2(15)		NOT NULL
);
CREATE TABLE "REPLY" (
	"REPLY_ID"	NUMBER		NOT NULL,
	"REPLY_POST"	VARCHAR2(1000)		NOT NULL,
	"REPLY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"REPLY_DEL"	CHAR(1)	DEFAULT 'Y'	NULL,
	"PST_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "LIKE" (
	"MENU_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);
CREATE TABLE "FILE" (
	"FILE_ID"	NUMBER		NULL,
	"FILE_INSTROG"	VARCHAR2(255)		NULL,
	"FILE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"THUMBNAIL"	NUMBER		NULL,
	"PST_ID"	NUMBER		NOT NULL
);
CREATE TABLE "PST_CATEGORY" (
	"POSTLIST"	NUMBER		NOT NULL,
	"PST_LISTALL"	VARCHAR2(30)		NULL
);
-------------------------
----- 회원 등급 테이블 -----
-------------------------
CREATE TABLE MEMBER_GRADE(
    MEMBER_CODE CHAR(1) PRIMARY KEY,
    GRADE_NAME VARCHAR2(12) NOT NULL UNIQUE,
    POINT_MIN NUMBER NOT NULL,
    POINT_MAX NUMBER NOT NULL
);

COMMENT ON COLUMN MEMBER_GRADE.MEMBER_CODE IS '회원등급코드';
COMMENT ON COLUMN MEMBER_GRADE.GRADE_NAME IS '회원등급명';
COMMENT ON COLUMN MEMBER_GRADE.POINT_MIN IS '최저점';
COMMENT ON COLUMN MEMBER_GRADE.POINT_MAX IS '최고점';

-- 더미데이터
INSERT INTO MEMBER_GRADE VALUES('1', '준회원', 0, 20);
INSERT INTO MEMBER_GRADE VALUES('2', '정회원', 21, 40);
INSERT INTO MEMBER_GRADE VALUES('3', '우수회원', 41, 80);
INSERT INTO MEMBER_GRADE VALUES('4', '특별회원', 81, 100);
-----------------------------

CREATE TABLE "REPLY_REPORT" (
	"RR_NO"	NUMBER		NOT NULL,
	"RR_HISTORY"	VARCHAR2(1000)		NOT NULL,
	"RR_TYPE"	NUMBER	DEFAULT 1	NULL,
	"RR_ANSWER"	VARCHAR2(1000)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPLY_ID"	NUMBER		NULL
);
CREATE TABLE "REPLY_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPLY_ID"	NUMBER		NULL
);
CREATE TABLE "POST_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PST_ID"	NUMBER		NOT NULL
);
CREATE TABLE "MEMBER_REPORT" (
	"MR_NO"	NUMBER		NOT NULL,
	"MR_HISTORY"	VARCHAR2(1000)		NULL,
	"MR_TYPE"	NUMBER	DEFAULT 1	NOT NULL,
	"MR_ANSWER"	VARCHAR2(1000)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NO2"	NUMBER		NOT NULL
);






















------------------------------------------------



ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);
ALTER TABLE "MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY (
	"MENU_ID"
);
ALTER TABLE "STORE" ADD CONSTRAINT "PK_STORE" PRIMARY KEY (
	"STORE_ID"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);
ALTER TABLE "NOTICEBOARD_POST" ADD CONSTRAINT "PK_NOTICEBOARD_POST" PRIMARY KEY (
	"PST_ID"
);
ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"ASK_NO"
);
ALTER TABLE "BRAND" ADD CONSTRAINT "PK_BRAND" PRIMARY KEY (
	"BRAND_ID"
);
ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_ID"
);
ALTER TABLE "FILE" ADD CONSTRAINT "PK_FILE" PRIMARY KEY (
	"FILE_ID"
);
ALTER TABLE "PST_CATEGORY" ADD CONSTRAINT "PK_PST_CATEGORY" PRIMARY KEY (
	"POSTLIST"
);
ALTER TABLE "MEMBER_GRADE" ADD CONSTRAINT "PK_MEMBER_GRADE" PRIMARY KEY (
	"MEMBER_CODE"
);
ALTER TABLE "REPLY_REPORT" ADD CONSTRAINT "PK_REPLY_REPORT" PRIMARY KEY (
	"RR_NO"
);
ALTER TABLE "MEMBER_REPORT" ADD CONSTRAINT "PK_MEMBER_REPORT" PRIMARY KEY (
	"MR_NO"
);
ALTER TABLE "MENU" ADD CONSTRAINT "FK_STORE_TO_MENU_1" FOREIGN KEY (
	"STORE_ID"
)
REFERENCES "STORE" (
	"STORE_ID"
);
ALTER TABLE "STORE" ADD CONSTRAINT "FK_BRAND_TO_STORE_1" FOREIGN KEY (
	"BRAND_ID"
)
REFERENCES "BRAND" (
	"BRAND_ID"
);
-----------------------
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_NB_POST_TO_RPT_1" FOREIGN KEY (
	"PST_ID"
)
REFERENCES "NOTICEBOARD_POST" (
	"PST_ID"
);
-----------------------
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

---------------------------------
ALTER TABLE "NOTICEBOARD_POST" ADD CONSTRAINT "FK_MB_TO_NB_POST_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
---------------------------------

ALTER TABLE "NOTICEBOARD_POST" ADD CONSTRAINT "FK_PST_CAT_TO_NB_POST_1" FOREIGN KEY (
	"POSTLIST"
)
REFERENCES "PST_CATEGORY" (
	"POSTLIST"
);

-------------------------------------


ALTER TABLE "QNA" ADD CONSTRAINT "FK_MEMBER_TO_QNA_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "REPLY" ADD CONSTRAINT "FK_NOTICEBOARD_POST_TO_REPLY_1" FOREIGN KEY (
	"PST_ID"
)
REFERENCES "NOTICEBOARD_POST" (
	"PST_ID"
);
ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MENU_TO_LIKE_1" FOREIGN KEY (
	"MENU_ID"
)
REFERENCES "MENU" (
	"MENU_ID"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "FILE" ADD CONSTRAINT "FK_NOTICEBOARD_POST_TO_FILE_1" FOREIGN KEY (
	"PST_ID"
)
REFERENCES "NOTICEBOARD_POST" (
	"PST_ID"
);
ALTER TABLE "REPLY_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "REPLY_REPORT" ADD CONSTRAINT "FK_REPLY_TO_REPLY_REPORT_1" FOREIGN KEY (
	"REPLY_ID"
)
REFERENCES "REPLY" (
	"REPLY_ID"
);
ALTER TABLE "REPLY_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "REPLY_LIKE" ADD CONSTRAINT "FK_REPLY_TO_REPLY_LIKE_1" FOREIGN KEY (
	"REPLY_ID"
)
REFERENCES "REPLY" (
	"REPLY_ID"
);
ALTER TABLE "POST_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_POST_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

---------------------------------
ALTER TABLE "POST_LIKE" ADD CONSTRAINT "FK_NBP_LIKE_1" FOREIGN KEY ("PST_ID")
REFERENCES "NOTICEBOARD_POST" ("PST_ID");
---------------------------------

ALTER TABLE "MEMBER_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "MEMBER_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_REPORT_2" FOREIGN KEY (
	"MEMBER_NO2"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);